-- liquibase formatted sql

-- changeset torkov:create_schema
create table if not exists cft2j02.public.users
(
    id       integer generated by default as identity constraint users_pk primary key,
    username varchar,
    fio      varchar
);

create table if not exists cft2j02.public.logins
(
    id          integer generated by default as identity constraint logins_pk primary key,
    access_date timestamp,
    user_id     integer constraint logins_users_id_fk references users,
    application varchar
);

-- rollback drop table cft2j02.public.logins;
-- rollback drop table cft2j02.public.users;